epicuri/cpe/epicuriCPE/Models/BusinessIntelligence.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using epicuri.Core.DatabaseModel;

namespace epicuri.CPE.Models
{
    public class BusinessIntelligence
    {
        public Restaurant restaurant;

        private epicuriContainer db = new epicuriContainer();

        public Dictionary<string, Dictionary<string, double>> Panel1;

        public Dictionary<string, List<KeyValuePair<Core.DatabaseModel.MenuItem, int>>> Panel2;

        public Dictionary<string, Dictionary<string, double>> Panel3;

        public Dictionary<string, double> Panel4;

        public bool week = false;
        public bool month = false;
        public bool threeMonths = false;
        public bool year = false;
        public bool forever = false;

        public bool showFilters = false;
        public bool fromWebView = false;

        public string filteredBy;
    }

    public class Panel2Data
    {
        public string Name;
        public int Count;
    }
}

epicuri/cpe/epicuriCPE/Controllers/BusinessIntelligenceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using epicuri.Core.DatabaseModel;
using epicuri.CPE.Models;
using System.Data.Objects;

namespace epicuri.CPE.Controllers
{
    public class BusinessIntelligenceController : Models.EpicuriController
    {
        public enum FilterPeriod
        {
            Week = 0, 
            Month, 
            ThreeMonths, 
            Year,
            Forever
        };

        [RequiresAuth("")]
        public ActionResult Index(string Auth, int Period = -1, bool webView = false)
        {
            try
            {
                DoAuth(Auth);

                BusinessIntelligence bi = new BusinessIntelligence();

                bi.restaurant = this.Restaurant;

                //Dynamically changed from Query String -- TODO

                FilterPeriod period = (FilterPeriod)Period;
                int daysAdded = 0;

                switch (period)
                {
                    case FilterPeriod.Week:
                        {
                            daysAdded = 7;
                            bi.week = true;
                        }
                        break;
                    case FilterPeriod.Month:
                        {
                            daysAdded = 30;
                            bi.month = true;
                        }
                        break;
                    case FilterPeriod.ThreeMonths:
                        {
                            daysAdded = 90;
                            bi.threeMonths = true;
                        }
                        break;
                    case FilterPeriod.Year:
                        {
                            daysAdded = 365;
                            bi.year = true;
                        }
                        break;

                    case FilterPeriod.Forever:
                    default:
                        {
                            daysAdded = 1000000;
                            bi.forever = true;
                        }
                        break;
                }

                if (Period == -1)
                {
                    bi.showFilters = true;
                    bi.forever = false;
                }
                else
                {
                    bi.showFilters = false;
                }

                if (webView)
                {
                    bi.fromWebView = true;
                }
                else
                {
                    bi.fromWebView = false;
                }

                bi.filteredBy = "Filtered By: " + period.ToString();

                bi.Panel1 = new Dictionary<string, Dictionary<string, double>>();

                // Get the data for Panel 1
                foreach (DayOfWeek day in Enum.GetValues(typeof(DayOfWeek)))
                {
                    if (!bi.Panel1.ContainsKey(day.ToString()))
                        bi.Panel1.Add(day.ToString(), new Dictionary<string, double>());

                    //Average # Seated
                    // TODO 
                    int noSeated = this.Restaurant.Sessions.Count(sess =>
                        sess.StartTime.DayOfWeek == day &&
                        // EP-663
                        !sess.RemoveFromReports &&
                        sess.StartTime.AddDays(daysAdded) >= DateTime.UtcNow &&
                        sess.GetType() == typeof(Core.DatabaseModel.SeatedSession) &&
                        sess.Paid == true &&
                        sess.Orders.Count != 0
                        );

                    bi.Panel1[day.ToString()].Add("seated", noSeated);
                    
                    //Average # Collected
                    int noCollected = this.Restaurant.Sessions.Count(sess =>
                        sess.StartTime.DayOfWeek == day &&
                        // EP-663
                        !sess.RemoveFromReports &&
                        sess.StartTime.AddDays(daysAdded) >= DateTime.UtcNow &&
                        sess.Orders.Count != 0 &&
                        sess.Paid == true &&
                        sess.GetType() == typeof(Core.DatabaseModel.TakeAwaySession) &&
                        ((Core.DatabaseModel.TakeAwaySession)sess).Delivery == false
                        );

                    bi.Panel1[day.ToString()].Add("collected", noCollected);

                    //Average # Deliveries
                    int noDeliveries = this.Restaurant.Sessions.Count(sess =>
                        sess.StartTime.DayOfWeek == day &&
                        !sess.RemoveFromReports &&
                            // EP-663
                        sess.StartTime.AddDays(daysAdded) >= DateTime.UtcNow &&
                        sess.Orders.Count != 0 &&
                        sess.Paid == true &&
                        sess.GetType() == typeof(Core.DatabaseModel.TakeAwaySession) &&
                        ((Core.DatabaseModel.TakeAwaySession)sess).Delivery == true
                        );

                    bi.Panel1[day.ToString()].Add("deliveries", noDeliveries);
                }

                // Get the data for Panel 2

                bi.Panel2 = new Dictionary<string, List<KeyValuePair<Core.DatabaseModel.MenuItem, int>>>();
                // EP-663
                var orders = Restaurant.Sessions.Where(sess => !sess.RemoveFromReports && sess.StartTime.AddDays(daysAdded) >= DateTime.UtcNow && sess.Paid == true).SelectMany(sess => sess.Orders);

                var foodResult = from ord in orders
                                 where ord.MenuItem.MenuItemTypeId == (int)epicuri.Core.DatabaseModel.Enums.MenuItemType.Food
                                 group ord by ord.MenuItem into menuItems
                                 orderby menuItems.Count() descending
                                 select new KeyValuePair<Core.DatabaseModel.MenuItem, int>(menuItems.Key, menuItems.Count());

                var drinkResult = from ord in orders
                                  where ord.MenuItem.MenuItemTypeId == (int)epicuri.Core.DatabaseModel.Enums.MenuItemType.Drink
                                  group ord by ord.MenuItem into menuItems
                                  orderby menuItems.Count() descending
                                  select new KeyValuePair<Core.DatabaseModel.MenuItem, int>(menuItems.Key, menuItems.Count());

                bi.Panel2.Add("food", foodResult.Take(5).ToList());
                bi.Panel2.Add("drink", drinkResult.Take(5).ToList());

                // Get the data for Panel 3

                bi.Panel3 = new Dictionary<string, Dictionary<string, double>>();

                DateTime firstSunday = new DateTime(1753, 1, 7);

                foreach (DayOfWeek day in Enum.GetValues(typeof(DayOfWeek)))
                {
                    if (!bi.Panel3.ContainsKey(day.ToString()))
                        bi.Panel3.Add(day.ToString(), new Dictionary<string, double>());
                    // EP-663
                    var orders2 = Restaurant.Sessions
                                  .Where(sess => !sess.RemoveFromReports && sess.StartTime.DayOfWeek == day && sess.StartTime.AddDays(daysAdded) >= DateTime.UtcNow && sess.Paid == true)
                                  .SelectMany(sess => sess.Orders);

                    //   Calculating the Average Food
                    var food = from ord in orders2
                               where ord.MenuItem.MenuItemTypeId == (int)epicuri.Core.DatabaseModel.Enums.MenuItemType.Food
                               select ord;

                    int foodCount = food.Count();
                    double foodSum = food.Sum(f => f.MenuItem.Price);

                    bi.Panel3[day.ToString()].Add("food", Math.Round(foodSum/foodCount, 2));

                    // Calculation the Average Drink
                    var drink = from ord in orders2
                                where ord.MenuItem.MenuItemTypeId == (int)epicuri.Core.DatabaseModel.Enums.MenuItemType.Drink
                               select ord;

                    int drinkCount = drink.Count();
                    double drinkSum = drink.Sum(f => f.MenuItem.Price);

                    bi.Panel3[day.ToString()].Add("drink", Math.Round(drinkSum / drinkCount, 2));
                }

                // Get the data for Panel 4

                bi.Panel4 = new Dictionary<string, double>();

                // Number of Self Service orders
                var seatedSelfService = Restaurant.Sessions.Where(sess => !sess.RemoveFromReports && sess.GetType() == typeof(Core.DatabaseModel.SeatedSession) && sess.Paid == true && sess.StartTime.AddDays(daysAdded) >= DateTime.UtcNow).SelectMany(sess => sess.Orders);
                int noItems = seatedSelfService.Count(items => items.InstantiatedFromId == 1 || items.InstantiatedFromId == 2);

                // Number of Takeaway/Delviery orders
                var takeawaySelfService = from tss in Restaurant.Sessions
                                          where tss.GetType() == typeof(Core.DatabaseModel.TakeAwaySession) && (tss.InstantiatedFromId == 1 || tss.InstantiatedFromId == 2) &&
                                              // EP-663
                                          tss.StartTime.AddDays(daysAdded) >= DateTime.UtcNow &&
                                          tss.Paid == true
                                          select tss;
                int takeawayOrders = takeawaySelfService.Count();

                // Number of reservations created via the diner app -- only counts the number of reservations that have arrived (i.e ArrivedTime != Null)
                var reservationSelfService = from res in db.Parties
                                             where res.RestaurantId == Restaurant.Id &&
                                             res.ArrivedTime != null &&

epicuri/cpe/epicuriCPE/Views/BusinessIntelligence/Index.cshtml
@model epicuri.CPE.Models.BusinessIntelligence


@{
    
    Layout = "~/Views/PortalBI.cshtml";

}

   @Styles.Render("~/Content/BI.css")
    <!--meta http-equiv="refresh" content="10"-->
 
    <!--Load the AJAX API-->
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript">
        google.load('visualization', '1.0', { 'packages': ['corechart'] });
        google.setOnLoadCallback(drawChart);



        function drawChart() {

            // Panel 1 data
            var data = google.visualization.arrayToDataTable([
            ['Day', 'Seated', 'Collected', 'Deliveries'],
            @foreach (var dataRow in Model.Panel1)
            {
                <text>
                    ['@dataRow.Key', @dataRow.Value["seated"], @dataRow.Value["collected"], @dataRow.Value["deliveries"]],
                </text>
            }
            ]);

              
            var options = {
                legend: { position: 'bottom' }
            };

            var chart = new google.visualization.ColumnChart(document.getElementById('chart_div'));
            chart.draw(data, options);

            // Panel 3 data
            var data2 = google.visualization.arrayToDataTable([
            ['Day', 'Food Items', 'Non Food Items'],
            @foreach (var dataRow in Model.Panel3)
            {
                <text>
                    ['@dataRow.Key', @dataRow.Value["food"], @dataRow.Value["drink"]],
                </text>
            }
            ]);


            var options2 = {
                'isStacked': true,
                legend: { position: 'bottom' }
            };

            var chart = new google.visualization.ColumnChart(document.getElementById('chart_div_contributions'));
            chart.draw(data2, options2);
        }

    </script>

    <div class="container">

        @if(Model.showFilters)
        {
        <table style="margin-top: 2em; margin-left: auto; margin-right: auto;">
            <tr>
                <td style="padding-left: 2em">
                    @using (Html.BeginForm("Index", "BusinessIntelligence", new { Period = 0, WebView = true }))
                    {
                        
                        if(Model.week == true)
                        {
                             <input type="submit" value="Week" name="Week" style="background-color: orange; width: 100px; height: 50px" />
                        }
                        else
                        {
                             <input type="submit" value="Week" name="Week" style="width: 100px; height: 50px"/>
                        }
                    }
                </td>
                <td style="padding-left: 2em">
                    @using (Html.BeginForm("Index", "BusinessIntelligence", new { Period = 1, WebView = true }))
                    {
                        if (Model.month == true)
                        {
                             <input type="submit" value="Month" name="Month" style="background-color: orange; width: 100px; height: 50px" />
                        }
                        else
                        {
                             <input type="submit" value="Month" name="Month" style="width: 100px; height: 50px"/>
                        }
                    }
                </td>
                <td style="padding-left: 2em">
                    @using (Html.BeginForm("Index", "BusinessIntelligence", new { Period = 2, WebView = true }))
                    {
                        if(Model.threeMonths == true)
                        {
                             <input type="submit" value="Three Months" name="Three Months" style="background-color: orange; width: 100px; height: 50px" />
                        }
                        else
                        {
                             <input type="submit" value="Three Months" name="Three Months" style="width: 100px; height: 50px" />
                        }
                    }
                </td>
                <td style="padding-left: 2em">
                    @using (Html.BeginForm("Index", "BusinessIntelligence", new { Period = 3, WebView = true }))
                    {
                        if(Model.year == true)
                        {
                             <input type="submit" value="Year" name="Year" style="background-color: orange; width: 100px; height: 50px" />
                        }
                        else
                        {
                             <input type="submit" value="Year" name="Year" style="width: 100px; height: 50px" />
                        }
                    }
                </td>
                <td style="padding-left: 2em">
                    @using (Html.BeginForm("Index", "BusinessIntelligence", new { Period = 4, WebView = true }))
                    {
                        if(Model.forever == true)
                        {
                             <input type="submit" value="Forever" name="Forever" style="background-color: orange; width: 100px; height: 50px" />
                        }
                        else
                        {
                             <input type="submit" value="Forever" name="Forever" style="width: 100px; height: 50px" />
                        }
                    }
                </td>
            </tr>
        </table>
        } else {
            
            if(Model.fromWebView)
            {
                <h3>@Model.filteredBy</h3>
            }
        <table class="frame">
            <tr>
                <td colspan="2">
                    <!-- Panel 1 -->
                    <h3>Average # of Sessions</h3>
                <!--    <table>
                        <thead>
                            <tr>
                                <td></td>
                                <td>Average # Seated</td>
                                <td>Average # Collections</td>
                                <td>Average # Deliveries</td>
                            </tr>
                        </thead>
                        @foreach (var dataRow in Model.Panel1)
                        {
                            <tr>
                                <td>@dataRow.Key</td>
                                <td>@dataRow.Value["seated"]</td>
                                <td>@dataRow.Value["collected"]</td>
                                <td>@dataRow.Value["deliveries"]</td>
                            </tr>
                        }
                        
                    </table> -->
                    <div id="chart_div"></div>
                    <hr />
                </td>
            </tr>
            <tr>
                <td style="width: 50%">
                    <!-- Panel 2 -->
                    <h3>Top Food Items</h3>
                    <table>
                        <thead>
                            <tr>
                                <td style="text-align: center; font-weight:bold;">Name</td>
                                <td style="text-align: center; font-weight:bold; padding-left: 3em;">#&nbsp;Ordered</td>
                            </tr>
                        </thead>
                        @foreach (var dataRow in Model.Panel2["food"])
                        {
                            <tr>
                                <td style="text-align: center;">@dataRow.Key.Name</td>
                                <td style="text-align: center; padding-left: 3em;">@dataRow.Value</td>
                            </tr>
                        }

                    </table>
                  </td>
                    <td style="width: 50%">
                    <h3>Top Drink Items</h3>
                    <table>
                        <thead>
                            <tr>
                                <td style="text-align: center; font-weight:bold;">Name</td>
                                <td style="text-align: center; font-weight:bold; padding-left: 3em;">#&nbsp;Ordered</td>
                            </tr>
                        </thead>
                        @foreach (var dataRow in Model.Panel2["drink"])
                        {
                            <tr>
                                <td style="text-align: center;">@dataRow.Key.Name</td>
                                <td style="text-align: center; padding-left: 3em;">@dataRow.Value</td>
                            </tr>
                        }

                    </table>
                    
                </td>
            </tr>
            <tr>
                <td colspan="2"><hr /></td>
            </tr>
            <tr>
                
                <td colspan="2">
                    <!-- Panel 3 -->
                    <h3>Average # of Items Ordered</h3>
   <!--                 <table>
                        <thead>
                            <tr>
                                <td>Day</td>
                                <td>Average £ contribution from food items</td>
                                <td>Average £ contribution from non food items</td>
                            </tr>
                        </thead>
                        @foreach (var dataRow in Model.Panel3)
                        {
                            <tr>
                                <td>@dataRow.Key</td>
                                <td>@dataRow.Value["food"]</td>
                                <td>@dataRow.Value["drink"]</td>
                            </tr>
                        }
                    </table>  --> 
                    <div id="chart_div_contributions"></div>
                    <hr />
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <h3>Self Service Summary</h3>
                </td>
                </tr>
            <tr>
                <td>
                    <table class="table-c">
                        <tr>
                            <td>Epicuri has helped you capture</td>
                        </tr>
                        <tr>
                            <td><h1>@Model.Panel4["Menu Items via Self Service"]</h1></td>
                        </tr>
                        <tr>
                            <td>Items via seated self service</td>
                        </tr>
                    </table>
                </td>
                <td>
         
                    <table class="table-c">
                        <tr>
                            <td>Epicuri has helped diners reserve</td>
                        </tr>
                        <tr>
                            <td><h1>@Model.Panel4["No. of Reservations"]</h1></td>
                        </tr>
                        <tr>
                            <td>tables at your restaurant</td>
                        </tr>
                    </table>
                </td>
            </tr>
            <tr>
                <td>
                    <table class="table-c">
                        <tr>
                            <td>Epicuri has helped you serve</td>
                        </tr>
                        <tr>
                            <td><h1>@Model.Panel4["Takeaways/Delivery Orders"]</h1></td>
                        </tr>
                        <tr>
                            <td>Takeaways booked via self service</td>
                        </tr>
                    </table>
                </td>
                <td>
                    <table class="table-c">
                        <tr>
                            <td>Epicuri has help you book</td>
                        </tr>
                        <tr>
                            <td><h1>@Model.Panel4["Revenue via Self Service"].ToString("0.00") @Model.restaurant.ISOCurrency</h1></td>
                        </tr>
                        <tr>
                            <td>in revenue via self service</td>
                        </tr>
                    </table>
                </td>
            </tr>

            <!--

            <tr class="spaceUnder">
                <td colspan="2">
                    <h3>Summary Information</h3>
                    <table>
                    <thead>
                         
                            @foreach (var dataRow in Model.Panel4)
                            {
                                <tr>
                                    <td>@dataRow.Key</td>
                                    @if (dataRow.Key.Equals("Revenue via Self Service"))
                                    {
                                        <td>@dataRow.Value.ToString("0.00") @Model.restaurant.ISOCurrency</td>
                                    }
                                    else
                                    {
                                        <td>@dataRow.Value</td>
                                    }
                                </tr>
                            }
                            
                        </thead>
                        </table>
                </td>
            </tr>

                -->
        </table>
            }
    </div>