epicuri/cpe/epicuriOnBoarding/Models/BlackoutsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace epicuriOnBoarding.Models
{
    public class BlackoutsViewModel
    {
        List<epicuri.Core.DatabaseModel.DateConstraint> Constraints;
        public int RestaurantId;
        public BlackoutsViewModel(int id, List<epicuri.Core.DatabaseModel.DateConstraint> constraints)
        {
            RestaurantId = id;
            Constraints = constraints;
        }

        public List<epicuri.Core.DatabaseModel.AbsoluteDateConstraint> AbsoluteTakeaway
        {
            get
            {
                return Constraints.OfType<epicuri.Core.DatabaseModel.AbsoluteDateConstraint>().Where(d => d.TargetSession).ToList();
            }
        }

        public List<epicuri.Core.DatabaseModel.AbsoluteDateConstraint> AbsoluteReservation
        {
            get
            {
                return Constraints.OfType<epicuri.Core.DatabaseModel.AbsoluteDateConstraint>().Where(d => !d.TargetSession).ToList();
            }
        }

        public List<epicuri.Core.DatabaseModel.DayOfWeekConstraint> DayOfWeekTakeaway
        {
            get
            {
                return Constraints.OfType<epicuri.Core.DatabaseModel.DayOfWeekConstraint>().Where(d => d.TargetSession).ToList();
            }
        }

        public List<epicuri.Core.DatabaseModel.DayOfWeekConstraint> DayOfWeekReservation
        {
            get
            {
                return Constraints.OfType<epicuri.Core.DatabaseModel.DayOfWeekConstraint>().Where(d => !d.TargetSession).ToList();
            }
        }

        public List<epicuri.Core.DatabaseModel.DayOfYearConstraint> DayOfYearTakeaway
        {
            get
            {
                return Constraints.OfType<epicuri.Core.DatabaseModel.DayOfYearConstraint>().Where(d => d.TargetSession).ToList();
            }
        }

        public List<epicuri.Core.DatabaseModel.DayOfYearConstraint> DayOfYearReservation
        {
            get
            {
                return Constraints.OfType<epicuri.Core.DatabaseModel.DayOfYearConstraint>().Where(d => !d.TargetSession).ToList();
            }
        }

    }
}

epicuri/cpe/epicuriOnBoarding/Controllers/FloorController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using epicuri.Core.DatabaseModel;
using epicuriOnBoarding.Filters;
namespace epicuriOnBoarding.Controllers
{
    [Authorize]
    [InitializeSimpleMembership]
    public class FloorController : Controller
    {
        private epicuriContainer db = new epicuriContainer();

        //
        // GET: /Floor/

        public ActionResult Index()
        {
            var floors = db.Floors.Include("Restaurant");
            return View(floors.ToList());
        }

        //
        // GET: /Floor/Details/5

        public ActionResult Details(int id = 0)
        {
            Floor floor = db.Floors.Single(f => f.Id == id);
            if (floor == null)
            {
                return HttpNotFound();
            }
            return View(floor);
        }

        //
        // GET: /Floor/Create

        public ActionResult Create(string id)
        {
            int rid = int.Parse(id);
 

            Restaurant r = db.Restaurants.Single(a => a.Id == rid);

            try
            {
                
                if (r == null)
                {
                    return HttpNotFound();
                }
            }
            catch { return HttpNotFound(); }

            ViewData["name"] = r.Name;

            ViewBag.RestaurantId = new SelectList(db.Restaurants, "Id", "Name");
            return View();
        }

        //
        // POST: /Floor/Create

        [HttpPost]
        public ActionResult Create(int id, Floor floor)
        {
            Restaurant r = db.Restaurants.Single(a => a.Id == id);
            if (r == null)
            {
                return HttpNotFound();
            }
            


            try
            {
                System.IO.Directory.CreateDirectory(Server.MapPath("~/static/"));
            }
            catch { }


            HttpPostedFileBase image = Request.Files[0];
            
            Guid g = Guid.NewGuid();

            System.IO.FileStream f = new System.IO.FileStream(Server.MapPath("~/static/") + g.ToString() + System.IO.Path.GetExtension(image.FileName), System.IO.FileMode.OpenOrCreate);
            image.InputStream.CopyTo(f);
            f.Close();

            try
            {
                System.Drawing.Image img = System.Drawing.Image.FromFile(Server.MapPath("~/static/") + g.ToString() + System.IO.Path.GetExtension(image.FileName));

                if (img.Height == 0)
                {
                    throw new Exception("file not image");
                }

                img.Dispose();


                Resource res = new Resource { CDNUrl = "http://cdn.epicuri.co.uk/" + g.ToString() + System.IO.Path.GetExtension(image.FileName), RestaurantId = id };
                db.AddToResources(res);

                db.SaveChanges();

                floor.RestaurantId = id;
                floor.Resource = res;

                db.SaveChanges();

                //EP-71
                Layout layout = new Layout
                {
                    Name = "TRANSIENT",
                    Temporary = true,
                    LastModified = DateTime.UtcNow,
                    FloorId = floor.Id
                };

                db.AddToLayouts(layout);
                db.SaveChanges();

                floor.LayoutId = layout.Id;
                db.SaveChanges();

                return RedirectToAction("Floors", "Restaurant", new { id = floor.RestaurantId });
            


            }
            catch (Exception e)
            {
                /*
                 * TODO file not image exception
                 */
                var a = e;
                System.IO.File.Delete(Server.MapPath("~/static/") + g.ToString() + System.IO.Path.GetExtension(image.FileName));
            }

            ViewData["id"] = id;
            ViewData["name"] = r.Name;
            ViewBag.RestaurantId = new SelectList(db.Restaurants, "Id", "Name", floor.RestaurantId);
            return View(floor);
        }

        
        public ActionResult Picture(int id = 0)
        {
            Floor floor = db.Floors.Single(f => f.Id == id);
            if (floor == null)
            {
                return HttpNotFound();
            }
       
            try
            {
                System.IO.Directory.CreateDirectory(Server.MapPath("~/static/"));
            }
            catch { }

            try
            {
                HttpPostedFileBase image = Request.Files[0];


                Guid g = Guid.NewGuid();

                System.IO.FileStream fs = new System.IO.FileStream(Server.MapPath("~/static/") + g.ToString() + System.IO.Path.GetExtension(image.FileName), System.IO.FileMode.OpenOrCreate);
                image.InputStream.CopyTo(fs);
                fs.Close();

                try
                {
                    System.Drawing.Image img = System.Drawing.Image.FromFile(Server.MapPath("~/static/") + g.ToString() + System.IO.Path.GetExtension(image.FileName));

                    if (img.Height == 0)
                    {
                        throw new Exception("file not image");
                    }

                    img.Dispose();



                    Resource res = new Resource { CDNUrl = "http://cdn.epicuri.co.uk/" + g.ToString() + System.IO.Path.GetExtension(image.FileName), RestaurantId = floor.RestaurantId };
                    db.AddToResources(res);
                    db.SaveChanges();

                    try
                    {
                        string oldpath = floor.Resource.CDNUrl;
                        int oldid = floor.Resource.Id;

                        db.Resources.DeleteObject(floor.Resource);
                        System.IO.File.Delete(Server.MapPath("~/static/") + oldpath.Substring("http://cdn.epicuri.co.uk/".Length));
                    }
                    catch { }
                    floor.Resource = res;
                    db.SaveChanges();
                    return RedirectToAction("Floors", "Restaurant", new { id = floor.RestaurantId });



                }
                catch(Exception e)
                {
                    var a = e;
                    /*
                     * TODO file not image exception
                     */

                    System.IO.File.Delete(Server.MapPath("~/static/") + g.ToString() + System.IO.Path.GetExtension(image.FileName));
                }
            }
            catch { }
            ViewBag.RestaurantId = new SelectList(db.Restaurants, "Id", "Name", floor.RestaurantId);
            return View(floor);
        }



        //
        // GET: /Floor/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Floor floor = db.Floors.Single(f => f.Id == id);
            if (floor == null)
            {
                return HttpNotFound();
            }
            ViewBag.RestaurantId = new SelectList(db.Restaurants, "Id", "Name", floor.RestaurantId);
            return View(floor);
        }

        //
        // POST: /Floor/Edit/5

        private int GetResourceId(int FloorId)
        {
            using (db = new epicuriContainer())
            {
                return db.Floors.Single(f => f.Id == FloorId).ResourceId;
            }

        }
        [HttpPost]
        public ActionResult Edit(Floor floor)
        {
            if (ModelState.IsValid)
            {
                floor.ResourceId = GetResourceId(floor.Id);
                db = new epicuriContainer();
                db.Floors.Attach(floor);
                db.ObjectStateManager.ChangeObjectState(floor, EntityState.Modified);
                db.SaveChanges();
                return RedirectToAction("Floors", "Restaurant", new { id = floor.RestaurantId });
              
            }
            ViewBag.RestaurantId = new SelectList(db.Restaurants, "Id", "Name", floor.RestaurantId);
            return View(floor);
        }

        //
        // GET: /Floor/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Floor floor = db.Floors.Single(f => f.Id == id);
            if (floor == null)
            {
                return HttpNotFound();
            }

            var floorQuery = db.Floors.Where(f => f.RestaurantId == floor.RestaurantId);

            if (floorQuery.ToList().Count == 1)
            {
                ViewBag.StatusMessage = "WARNING: Deleting the last floor will disable the Restaurant for the Waiter App";
            }
            ViewBag.RestaurantId = floor.RestaurantId;
            return View(floor);
        }

        //
        // POST: /Floor/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Floor floor = db.Floors.Single(f => f.Id == id);

            //EP-110
            //Can't delete the floor because of the layout / TableLayout / Table / etc.

            /*
            floor.LayoutId = null;
            db.SaveChanges();

            var layouts = db.Layouts.Where(l => l.FloorId == id);
            List<Layout> layoutList = layouts.ToList();

            if (layoutList != null)
            {
                foreach (Layout l in layoutList)
                {
                    db.Layouts.DeleteObject(l);
                }
            }
            db.SaveChanges();
            db.Floors.DeleteObject(floor);
            */

            // So just mark the floor as deleted

            floor.Deleted = true;

            var floorQuery = db.Floors.Where(f => f.RestaurantId == floor.RestaurantId);
            var Restaurant = db.Restaurants.Single(r => r.Id == floor.RestaurantId);
           
            if (floorQuery.ToList().Count == 1)
            {
                Restaurant.EnabledForWaiter = false;
            }
           
            db.SaveChanges();

epicuri/cpe/epicuriOnBoarding/Controllers/PrinterController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using epicuri.Core.DatabaseModel;

namespace epicuriOnBoarding.Controllers
{
    public class PrinterController : Controller
    {
        private epicuriContainer db = new epicuriContainer();



        //
        // GET: /Printer/Create

        public ActionResult Create(string id)
        {
            int rid = int.Parse(id);


            Restaurant r = db.Restaurants.Single(a => a.Id == rid);

            try
            {

                if (r == null)
                {
                    return HttpNotFound();
                }
            }
            catch { return HttpNotFound(); }

            ViewBag.RestaurantId = r.Id;
            ViewData["name"] = r.Name;
            return View();
        }

        //
        // POST: /Printer/Create

        [HttpPost]
        public ActionResult Create(int id, Printer printer)
        {

            Restaurant r = db.Restaurants.Single(a => a.Id == id);
            if (r == null)
            {
                return HttpNotFound();
            }


            if (ModelState.IsValid)
            {
                // EP-751 clean out IP if it is a screen printer
                if (string.IsNullOrEmpty(printer.IP))
                    printer.IP = null;

                r.Printers.Add(printer);
                db.SaveChanges();
                return RedirectToAction("Printers", new { id = printer.RestaurantId, controller = "Restaurant" });
                //return RedirectToAction("Index","Restaurant");
            }

            ViewBag.RestaurantId = r.Id;
            return View(printer);
        }

        //
        // GET: /Printer/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Printer printer = db.Printers.Single(p => p.Id == id);
            if (printer == null)
            {
                return HttpNotFound();
            }
            ViewBag.RestaurantId = new SelectList(db.Restaurants.Where(r => r.Deleted == null), "Id", "Name", printer.RestaurantId);
            ViewBag.ReturnToRestaurant = printer.RestaurantId;
            return View(printer);
        }

        //
        // POST: /Printer/Edit/5

        [HttpPost]
        public ActionResult Edit(Printer printer)
        {
            if (ModelState.IsValid)
            {
                // EP-751 clean out IP if it is a screen printer
                if (string.IsNullOrEmpty(printer.IP))
                    printer.IP = null;

                db.Printers.Attach(printer);
                db.ObjectStateManager.ChangeObjectState(printer, EntityState.Modified);
                db.SaveChanges();
                
                //EP-108
                return RedirectToAction("Printers", new { id = printer.RestaurantId, controller = "Restaurant" });

                //return RedirectToAction("Index","Restaurant");
            }
            ViewBag.RestaurantId = new SelectList(db.Restaurants, "Id", "Name", printer.RestaurantId);
            return View(printer);
        }

        //
        // GET: /Printer/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Printer printer = db.Printers.Single(p => p.Id == id);
            if (printer == null)
            {
                return HttpNotFound();
            }

            var printerQuery = db.Printers.Where(p => p.RestaurantId == printer.RestaurantId);

            if (printerQuery.ToList().Count == 1)
            {
                ViewBag.StatusMessage = "WARNING: Deleting the last printer will disable the Restaurant for the Waiter App";
            }

            ViewBag.RestaurantId = printer.RestaurantId;
            return View(printer);
        }

        //
        // POST: /Printer/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Printer printer = db.Printers.Single(p => p.Id == id);

            var printerQuery = db.Printers.Where(p => p.RestaurantId == printer.RestaurantId);

            if (printerQuery.ToList().Count == 1)
            {
                var Restaurant = db.Restaurants.Single(r => r.Id == printer.RestaurantId);
                Restaurant.EnabledForWaiter = false;
            }

            var PrinterInUse = db.MenuItems.Where(mi => mi.RestaurantId == printer.RestaurantId && mi.PrinterId == printer.Id);

            if (PrinterInUse.ToList().Count != 0)
            {
                ViewBag.StatusMessage = "Unable to delete this printer (MenuItems are assigned to this printer)";
                ViewBag.RestaurantId = printer.RestaurantId;
                return View(printer);
            }

            var restPrinter = db.Restaurants.Single(r => r.Id == printer.RestaurantId);

            if (restPrinter.TakeawayPrinterId == id || restPrinter.BillingPrinterId == id)
            {
                ViewBag.StatusMessage = "Unable to delete this printer (This is the takeaway/billing printer)";
                ViewBag.RestaurantId = printer.RestaurantId;
                return View(printer);
            }


            db.Printers.DeleteObject(printer);
            db.SaveChanges();
           
            return RedirectToAction("Printers", new { controller = "Restaurant", id = printer.RestaurantId });
            //return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

epicuri/cpe/epicuriOnBoarding/Views/Restaurant/Blackouts.cshtml
@model epicuriOnBoarding.Models.BlackoutsViewModel

@{
    ViewBag.Title = "Blackouts";
}

<p>
    @Html.ActionLink("Create New Absolute Date Blackout", "Create", new { controller = "AbsoluteDateConstraint", id = Model.RestaurantId }) - @Html.ActionLink("Create New Day Of Week Blackout", "Create", new { controller = "DayOfWeekDateConstraint", id = Model.RestaurantId })
</p> 
<h1>Takeaway Blackouts</h1>
Absolute dates = specific day to disable takeaways (such as Christmas Day), whereas a day of week specifies that every tuesday, the takewaway wll be closed.<br />
Absolute Dates are in local time
<h2>Absolute Date</h2>

<table>
@if (Model.AbsoluteTakeaway.Count > 0)
{
    <tr>
       <!-- <th>
            For
        </th> -->
        <th>
             Start Date
        </th>
        <th>
            Start Time
        </th>
        <th>
             Blackout Duration
        </th>
        <th></th>
    </tr>
}
@foreach (var item in Model.AbsoluteTakeaway) {
    <tr>
       <!-- <td>
            @(item.TargetSession ? "Takeaway" : "Reservation")
        </td> -->
        <td>
            @Html.DisplayFor(modelItem => item.DateString)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LocalTime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BlackoutHours)hrs @Html.DisplayFor(modelItem => item.BlackoutMinutes)mins
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new {controller="AbsoluteDateConstraint", id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { controller = "AbsoluteDateConstraint", id = item.Id })
        </td>
    </tr>
}
</table>

<h2>Day Of Week</h2>


<table>
@if (Model.DayOfWeekTakeaway.Count > 0)
{
    <tr>
        <th>
            Day
        </th>
        <th>
            Start Time
        </th>
        <th>
             Blackout Duration
        </th>
        <th></th>
    </tr>
}
@foreach (var item in Model.DayOfWeekTakeaway) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Day)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StartTime)
        </td>
         <td>
            @Html.DisplayFor(modelItem => item.BlackoutHours)hrs @Html.DisplayFor(modelItem => item.BlackoutMinutes)mins
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { controller = "DayOfWeekDateConstraint", id = item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { controller = "DayOfWeekDateConstraint", id = item.Id })
        </td>
    </tr>
}
</table>

<h1>Reservation Blackouts</h1>
Absolute dates = specific day to disable reservations (such as Christmas Day), whereas a day of week specifies that every tuesday, the restaurant will not accept reservations.
<h2>Absolute</h2>
<table>
@if (Model.AbsoluteReservation.Count > 0)
{
    <tr>
        <th>
             Start Date
        </th>
        <th>
            Start Time
        </th>
        <th>
             Blackout Duration
        </th>
        <th></th>
    </tr>
}
@foreach (var item in Model.AbsoluteReservation) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.DateString)
        </td>
       <!-- <td>
            @(item.TargetSession ? "Takeaway" : "Reservation")
        </td> -->
        <td>
            @Html.DisplayFor(modelItem => item.LocalTime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BlackoutHours)hrs @Html.DisplayFor(modelItem => item.BlackoutMinutes)mins
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new {controller="AbsoluteDateConstraint", id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { controller = "AbsoluteDateConstraint", id = item.Id })
        </td>
    </tr>
}
</table>

<h2>Day Of Week</h2>

<table>
@if (Model.DayOfWeekReservation.Count > 0)
{
    <tr>
        <th>
            Day
        </th>
        <th>
            Start Time
        </th>
        <th>
             Blackout Duration
        </th>
        <th></th>
    </tr>
}
@foreach (var item in Model.DayOfWeekReservation){
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Day)
        </td>
        <!-- <td>
            @(item.TargetSession ? "Takeaway" : "Reservation")
        </td> -->
        <td>
            @Html.DisplayFor(modelItem => item.StartTime)
        </td>
         <td>
            @Html.DisplayFor(modelItem => item.BlackoutHours)hrs @Html.DisplayFor(modelItem => item.BlackoutMinutes)mins
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { controller = "DayOfWeekDateConstraint", id = item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { controller = "DayOfWeekDateConstraint", id = item.Id })
        </td>
    </tr>
}
</table>

epicuri/cpe/epicuriOnBoarding/Views/Restaurant/ClearOrders.cshtml
@model epicuri.Core.DatabaseModel.Restaurant
@{
    ViewBag.Title = "Restaurant";

}

<h2>Clear orders for @Model.Name</h2>



<h3>Restaurant Stats</h3>
<ul>

    <li>Sessions Count: @Model.Sessions.Count()</li>
    <li>Orders Count: @Model.Sessions.SelectMany(s=>s.Orders).Count()</li>
    <li>Payments Count: @Model.Sessions.SelectMany(s=>s.Adjustments).Count()</li>
</ul>

<form method="post">
    <input type="submit" value="Clear Orders"/>
</form>

epicuri/cpe/epicuriOnBoarding/Views/Restaurant/Delete.cshtml
@model epicuri.Core.DatabaseModel.Restaurant

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Restaurant</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Category.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Category.Name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Description)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Description)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ISOCurrency)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ISOCurrency)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Country.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Country.Name)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" />
        @Html.ActionLink("Back to List", "Index")
    </p>
}

epicuri/cpe/epicuriOnBoarding/Views/Restaurant/Details.cshtml
@model epicuri.Core.DatabaseModel.Restaurant

@{
    ViewBag.Title = Model.Name;
}

<h2>Details</h2>

<fieldset>
    <legend>Restaurant</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Category.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Category.Name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Description)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Description)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ISOCurrency)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ISOCurrency)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Country.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Country.Name)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id=Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

epicuri/cpe/epicuriOnBoarding/Views/Restaurant/Floors.cshtml
@model IEnumerable<epicuri.Core.DatabaseModel.Floor>

@{
    ViewBag.Title = "Index";
}

<h2>Floors for Restaurant @ViewData["name"]</h2>

<p>
    @Html.ActionLink("Create New", "Create", "Floor", new { id = ViewData["id"] }, null)
</p>
<table>
    <tr>
        <th>
            Floor Name
        </th>
        <th>
            URL
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Capacity)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Resource.CDNUrl)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Capacity)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", "Floor", new { id = item.Id },null) |
            @Html.ActionLink("Change Picture", "Picture", "Floor", new { id = item.Id },null) |
            @Html.ActionLink("Delete", "Delete", "Floor", new { id=item.Id },null)
        </td>
    </tr>
}

</table>

epicuri/cpe/epicuriOnBoarding/Views/Restaurant/Printers.cshtml
@model IEnumerable<epicuri.Core.DatabaseModel.Printer>
@{
    ViewBag.Title = "Printers";

}

<h2>Printers for Restaurant @ViewData["name"]</h2>

<p>
    @Html.ActionLink("Create New", "Create", "Printer", new { id = ViewData["id"] }, null)
</p>
<table>
    <tr>
        <th>
            Printer Name
        </th>
        <th>
            IP
        </th>
        <th>
            Type
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IP)
        </td>
        <td>
            @if (item.IP != null)
            {
                <span>Physical</span>
            }
            else
            {
                <span>Logical</span>
            }
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", "Printer", new { id = item.Id }, null) |
            @Html.ActionLink("Delete", "Delete", "Printer", new { id = item.Id }, null)
        </td>
    </tr>
}

</table>