epicuri/cpe/epicuriOnBoarding/Controllers/CountryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using epicuri.Core.DatabaseModel;
using epicuriOnBoarding.Filters;
namespace epicuriOnBoarding.Controllers
{
    [Authorize]
    [InitializeSimpleMembership]
    public class CountryController : Controller
    {
        private epicuriContainer db = new epicuriContainer();

        //
        // GET: /Country/

        public ActionResult Index()
        {
            return View(db.Countries.OrderBy(c => c.Name).ToList());
        }

        //
        // GET: /Country/Details/5

        public ActionResult Details(int id = 0)
        {
            Country country = db.Countries.Single(c => c.Id == id);
            if (country == null)
            {
                return HttpNotFound();
            }
            return View(country);
        }

        //
        // GET: /Country/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Country/Create

        [HttpPost]
        public ActionResult Create(Country country)
        {
            if (ModelState.IsValid)
            {
                var test = db.Countries.Where(ctry => ctry.Name.ToLower().Trim() == country.Name.ToLower().Trim() || ctry.Acronym == country.Acronym);
                if (test != null && test.Count() > 0)
                {
                    ViewBag.StatusMessage = "A Country with this name or acronym already exists";
                    return View(country);
                }
                
                db.Countries.AddObject(country);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(country);
        }

        //
        // GET: /Country/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Country country = db.Countries.Single(c => c.Id == id);
            if (country == null)
            {
                return HttpNotFound();
            }
            return View(country);
        }

        //
        // POST: /Country/Edit/5

        [HttpPost]
        public ActionResult Edit(Country country)
        {
            if (ModelState.IsValid)
            {
                db.Countries.Attach(country);
                db.ObjectStateManager.ChangeObjectState(country, EntityState.Modified);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(country);
        }

        //
        // GET: /Country/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Country country = db.Countries.Single(c => c.Id == id);
            if (country == null)
            {
                return HttpNotFound();
            }
            return View(country);
        }

        //
        // POST: /Country/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Country country = db.Countries.Single(c => c.Id == id);
            db.Countries.DeleteObject(country);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

epicuri/cpe/epicuriOnBoarding/Controllers/TaxController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using epicuri.Core.DatabaseModel;
using epicuriOnBoarding.Filters;
namespace epicuriOnBoarding.Controllers
{
    [Authorize]
    [InitializeSimpleMembership]
    public class TaxController : Controller
    {
        private epicuriContainer db = new epicuriContainer();

        //
        // GET: /Tax/

        public ActionResult Index()
        {
            var taxtypes = db.TaxTypes.Where(t => t.Deleted == null);
            return View(taxtypes.ToList());
        }

        //
        // GET: /Tax/Details/5

        public ActionResult Details(int id = 0)
        {
            TaxType taxtype = db.TaxTypes.Single(t => t.Id == id);
            if (taxtype == null)
            {
                return HttpNotFound();
            }
            return View(taxtype);
        }

        //
        // GET: /Tax/Create

        public ActionResult Create()
        {
            ViewBag.RestaurantId = new SelectList(db.Restaurants, "Id", "Name");
            ViewBag.CountryId = new SelectList(db.Countries.OrderBy(c => c.Name), "Id", "Name");
            return View();
        }

        //
        // POST: /Tax/Create

        [HttpPost]
        public ActionResult Create(TaxType taxtype)
        {
            if (ModelState.IsValid)
            {
                var test = db.TaxTypes.Where(tt => tt.Name.ToLower().Trim() == taxtype.Name.ToLower().Trim() && tt.CountryId == taxtype.CountryId && tt.Deleted == null);
                
                if (test != null && test.Count() > 0)
                {
                    ViewBag.StatusMessage = "A Tax Type with this name already exists for this country";
                    ViewBag.CountryId = new SelectList(db.Countries.OrderBy(c => c.Name), "Id", "Name");
                    return View(taxtype);
                }

                db.TaxTypes.AddObject(taxtype);
                db.SaveChanges();
                return RedirectToAction("Index");
            }


            ViewBag.CountryId = new SelectList(db.Countries, "Id", "Name");
            return View(taxtype);
        }

        //
        // GET: /Tax/Edit/5

        public ActionResult Edit(int id = 0)
        {
            TaxType taxtype = db.TaxTypes.Single(t => t.Id == id);
            if (taxtype == null)
            {
                return HttpNotFound();
            }

            ViewBag.CountryId = new SelectList(db.Countries.OrderBy(c => c.Name), "Id", "Name", taxtype.CountryId);
            return View(taxtype);
        }

        //
        // POST: /Tax/Edit/5

        [HttpPost]
        public ActionResult Edit(TaxType taxtype)
        {
            if (ModelState.IsValid)
            {
                TaxType currentRecord = db.TaxTypes.Where(tt => tt.Id == taxtype.Id).Single();
                db.TaxTypes.Detach(currentRecord);

                var test = db.TaxTypes.Where(tt => tt.Name.ToLower().Trim() == taxtype.Name.ToLower().Trim() && tt.CountryId == taxtype.CountryId && tt.Deleted == null);
                
                if (test != null && test.Count() > 0 && taxtype.Name != currentRecord.Name)
                {
                    ViewBag.StatusMessage = "A Tax Type with this name already exists for this country";
                    ViewBag.CountryId = new SelectList(db.Countries.OrderBy(c => c.Name), "Id", "Name");
                    return View(taxtype);
                }

                db.TaxTypes.Attach(taxtype);
                db.ObjectStateManager.ChangeObjectState(taxtype, EntityState.Modified);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            
            ViewBag.CountryId = new SelectList(db.Countries, "Id", "Name");
            return View(taxtype);
        }

        //
        // GET: /Tax/Delete/5

        public ActionResult Delete(int id = 0)
        {
            TaxType taxtype = db.TaxTypes.Single(t => t.Id == id);
            if (taxtype == null)
            {
                return HttpNotFound();
            }
            return View(taxtype);
        }

        //
        // POST: /Tax/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            TaxType taxtype = db.TaxTypes.Single(t => t.Id == id);
            taxtype.Deleted = DateTime.Today;
            
            //db.TaxTypes.DeleteObject(taxtype);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

epicuri/cpe/epicuriOnBoarding/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - Epicuri Management Portal</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Styles.Render("~/Content/jquery.timepicker.css")
        @Scripts.Render("~/bundles/modernizr")
        <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.1/themes/base/jquery-ui.css" />
  
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("epicuri", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            @if (Request.IsAuthenticated)
                            {
                            <li>@Html.ActionLink("Restaurants", "Index", "Restaurant")</li>
                            <li>@Html.ActionLink("Countries", "Index", "Country")</li>
                            <li>@Html.ActionLink("Cuisines", "Index", "Category")</li>
                            <li>@Html.ActionLink("Defaults", "Index", "Default")</li>
                            <li>@Html.ActionLink("Tax Types", "Index", "Tax")</li>
                            <li>@Html.ActionLink("Adj. Types", "Index", "AdjustmentType")</li>
                            <li>@Html.ActionLink("Users", "List", "Account")</li>
                            <li>@Html.ActionLink("Reset Pass.", "Index", "PasswordReset")</li>
                            }
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                <p class="message-success">@ViewBag.StatusMessage</p>
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.UtcNow.Year - Epicuri</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)

        @Scripts.Render("~/Content/jquery.timepicker.min.js")
        <script src="http://code.jquery.com/ui/1.10.1/jquery-ui.js"></script>
   <script>
       $(function () {
           $("#Date").datepicker({
               dateFormat: "dd/mm/yy",
               minDate: 0
           }
           );

           $("#EndDate").datepicker({
               dateFormat: "dd/mm/yy",
               minDate: 0
           }
           );

           $("#StartTime").timepicker(
               { 'timeFormat': 'H:i', 'scrollDefaultNow': true }
           
           );

           $("#LocalTime").timepicker(
               { 'timeFormat': 'H:i', 'scrollDefaultNow': true }

           );


           $("#EndTime").timepicker(
               { 'timeFormat': 'H:i', 'scrollDefaultNow': true }
           );
       });

       $(function () {
           $.validator.addMethod('date',
           function (value, element) {
               if (this.optional(element)) {
                   return true;
               }
               var ok = true;
               try {
                   $.datepicker.parseDate('dd/mm/yy', value);
               }
               catch (err) {
                   ok = false;
               }
               return ok;
           });
           $(".datefield").datepicker({ dateFormat: 'dd/mm/yy', changeYear: true });
       });
  </script>
    </body>
</html>